[package]
name = "e4e5"
version = "0.1.0"
edition = "2024"

[dependencies]
fighting_daisy = "0.2.0"
include_directory = "0.1.1"
maud = "0.27.0"
rocket = { version = "=0.5.1", features = ["json"] }
serde = "1.0.219"
serde_derive = "1.0.219"
uuid = { version = "1.16.0", features = ["v4"] }
